Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -22,7 +22,17 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 22
-          cache: npm
+
+      - name: Check project
+        run: |
+          echo "Node:"
+          node --version
+          echo "NPM:"
+          npm --version
+          echo "Project files:"
+          ls -la
+          echo "Package file:"
+          test -f package.json && echo "package.json found" || (echo "ERROR: package.json missing" && exit 1)
 
       - name: Install dependencies
         run: npm install
